#ifndef CONSTANTS_H
#define CONSTANTS_H
#include <iostream>
#include <QApplication>
#include <QAbstractSocket>
#include <QAction>
#include <QByteArray>
#include <QDebug>
#include <QDataStream>
#include <QDateTime>
#include <QFileDialog>
#include <QHostAddress>
#include <QIODevice>
#include <QMutexLocker>
#include <QMutex>
#include <QMenuBar>
#include <QMessageBox>
#include <QMainWindow>
#include <QNetworkProxy>
#include <QObject>
#include <QProcess>
#include <QSizePolicy>
#include <QString>
#include <QThread>
#include <QTimer>
#include <QtDebug>
#include <QtGui>
#include <QUdpSocket>
#include <QWaitCondition>
#include <QWidget>
#include <QFont>
#include <QFrame>
#include <QBitArray>
#include <QTcpSocket>
#include <QDir>
#include <QTabWidget>
#include <QtNetwork>
#include <QFileDialog>
// ******** Root *********
#include <TROOT.h>
#include <TBuffer.h>
#include <TApplication.h>
#include <TCanvas.h>
#include <TStyle.h>
#include <TLegend.h>
#include <TLatex.h>
#include <TH1.h>
#include <TH2.h>
#include <TF1.h>
#include <TH1D.h>
#include <TGraph.h>
#include <TGraphErrors.h>
#include <TMarker.h>
#include <TString.h>
#include <TFile.h>
#include <TMath.h>
#include <TLine.h>
#include <TBranch.h>
#include <TTree.h>
#include <TPad.h>
#include <TChain.h>
#include <TSystem.h>
#include <TRandom.h>
#include "TVector3.h"


//********* qtRoot ************
//#include <TQtWidget.h>

#endif // CONSTANTS_H
